// Generated by Wrangler by running `wrangler types`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface Env {
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}