// Generated by Wrangler by running `wrangler types`

interface Env {
	SUPABASE_URL: string;
	SUPABASE_KEY: string;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}