name: eq_server
description: Starting point for a Serverpod server.

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  serverpod: 2.3.1

dev_dependencies:
  altive_lints: ^1.19.1
  eqmonitor_lints:
    git:
      url: https://github.com/YumNumm/EQMonitor
      ref: develop
      path: packages/eqmonitor_lints
  serverpod_test: 2.3.1

  test: '^1.24.2'
