name: api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.3.0
  js_interop_utils: ^1.0.6
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_test_handler: ^2.0.2
  supabase: ^2.6.3
  web: ^1.1.1

dev_dependencies:
  altive_lints: ^1.19.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  eqmonitor_lints:
    git:
      url: https://github.com/YumNumm/EQMonitor
      ref: develop
      path: packages/eqmonitor_lints
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  shelf_router_generator: ^1.1.1

dependency_overrides:
  http:
    git:
      url: https://github.com/dart-lang/http.git
      ref: 29c5733014d8cc485a6b11b24c5b11ba172cb686
      path: pkgs/http
