name: api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  cf_workers:
    path: ../../cf_workers.dart/
  eq_server:
    path: ../packages/eq_server
  http: ^1.3.0
  supabase: ^2.6.3

dev_dependencies:
  altive_lints: ^1.19.1
  eqmonitor_lints:
    git:
      url: https://github.com/YumNumm/EQMonitor
      ref: develop
      path: packages/eqmonitor_lints
