name: api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  cf_workers:
    path: ../../cf_workers.dart/
  eq_api_client:
    path: ../../eq_api_client/
  http: ^1.3.0
  js_interop_utils: ^1.0.6
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_test_handler: ^2.0.2
  supabase: ^2.6.3

dev_dependencies:
  altive_lints: ^1.19.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  eqmonitor_lints:
    git:
      url: https://github.com/YumNumm/EQMonitor
      ref: develop
      path: packages/eqmonitor_lints
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  shelf_router_generator: ^1.1.1
